[metadata]
name = "Raiders"
entity_type = "Unit"

[offchain_metadata]
link = "Raiders.png"

[damage]
min_damage = 4
max_damage = 12
bonus_infantry = 0 
bonus_armor = 0 
bonus_aircraft = 1
bonus_feature = 0

[health]
health = 35

[troop_class]
class = "Armor"

[range]
movement = 3
attack_range = 3

[last_used]
last_used = 0
recovery = 4

[value]
value = 35