[metadata]
name = "Scout"
entity_type = "Unit"

[offchain_metadata]
link = "Scout.png"

[damage]
min_damage = 1
max_damage = 10
bonus_infantry = 0 
bonus_armor = 0 
bonus_aircraft = 0
bonus_feature = 0

[health]
health = 10

[troop_class]
class = "Infantry"

[range]
movement = 1
attack_range = 1

[last_used]
last_used = 0
recovery = 10

[value]
value = 10